spring:
  application:
    name: vitality-git
  datasource:
    url: jdbc:postgresql://localhost:5432/vitality-git
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: false

token:
  signing:
    key: ${SIGNING_TOKEN}
